### PR TITLE
WIP key export (with sbot updated)

### PR DESCRIPTION
**Pull request by mixmix**
I've tried this and seen it not work and work (just like the other versions of this).
I'm not convinced the indexing boosts in this new scuttlebot (and plugins) makes a significant improvement to restoring your identity....

### CODE REVIEW

**Comment by soapdog** [comment]
I am testing this branch right now, trying to restore my main identity. @mixmix I've read your other comment about db size, does this measure just your feed or the whole collection of feeds? because I believe that if this is the collection of feeds then tracking this number is a bit misleading as it will change as people in your FOAF graph keep posting stuff... am I right?

**Comment by soapdog** [comment]
With this branch, I am yet to see any content after I've restored my identity... My own personal information is right though.

**Comment by ticktackim** [comment]
@soapdog Why? Because your node is too remote even you connect with the Ticktack pubs?


原始邮件
发件人:Andre Alves Garzianotifications@github.com
收件人:ticktackim/ticktack-workplanticktack-workplan@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年5月30日(周三) 06:13
主题:Re: [ticktackim/ticktack-workplan] WIP key export (with sbot updated)(#150)


With this branch, I am yet to see any content after I've restored my identity... My own personal information is right though.

**Comment by soapdog** [comment]
I am testing this again.

**Pull request merged**
